# Generated by Django 4.1 on 2022-08-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.CharField(max_length=150)),
                ('kana', models.CharField(max_length=150)),
                ('roomaji', models.CharField(max_length=150)),
                ('english_text', models.CharField(max_length=150)),
                ('japanese_audio_path', models.FileField(upload_to='')),
                ('english_audio_path', models.FileField(upload_to='')),
            ],
        ),
    ]
